import { IAdminProductDataType, IAdminCategoryDataType, IAdminBrandDataType } from '@/lib/types/interfaces/apis/admin-product.interfaces';

/**
 * Mock products data for admin dashboard
 * In production, this would come from backend API
 */
export const mockAdminProducts: IAdminProductDataType[] = [
  {
    id: '1',
    name: 'Serum Vitamin C Brightening',
    slug: 'serum-vitamin-c-brightening',
    sku: 'SER-VIT-001',
    shortDesc: 'Serum dưỡng sáng da chứa 15% Vitamin C nguyên chất',
    basePrice: 450000,
    comparePrice: 550000,
    isActive: true,
    isFeatured: true,
    brand: { id: '1', name: 'LingBeauty', slug: 'lingbeauty' },
    category: { id: '1', name: 'Serum', slug: 'serum', parentId: null, isActive: true, sortOrder: 1 },
    primaryImage: '/images/products/serum-vitc.jpg',
    stock: 150,
    lowStockThreshold: 20,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-02-01T14:30:00Z',
  },
  {
    id: '2',
    name: 'Kem Chống Nắng SPF50+',
    slug: 'kem-chong-nang-spf50',
    sku: 'SUN-PRO-001',
    shortDesc: 'Kem chống nắng phổ rộng, bảo vệ da khỏi UVA/UVB',
    basePrice: 320000,
    comparePrice: 380000,
    isActive: true,
    isFeatured: false,
    brand: { id: '1', name: 'LingBeauty', slug: 'lingbeauty' },
    category: { id: '2', name: 'Chống nắng', slug: 'chong-nang', parentId: null, isActive: true, sortOrder: 2 },
    primaryImage: '/images/products/sunscreen.jpg',
    stock: 85,
    lowStockThreshold: 15,
    createdAt: '2024-01-20T09:00:00Z',
    updatedAt: '2024-02-02T11:00:00Z',
  },
  {
    id: '3',
    name: 'Sữa Rửa Mặt Dịu Nhẹ',
    slug: 'sua-rua-mat-diu-nhe',
    sku: 'CLN-GEN-001',
    shortDesc: 'Sữa rửa mặt dành cho da nhạy cảm, không gây kích ứng',
    basePrice: 180000,
    comparePrice: 220000,
    isActive: true,
    isFeatured: false,
    brand: { id: '2', name: 'PureSkin', slug: 'pureskin', logo: '/images/brands/pureskin.png' },
    category: { id: '3', name: 'Làm sạch', slug: 'lam-sach', parentId: null, isActive: true, sortOrder: 3 },
    primaryImage: '/images/products/cleanser.jpg',
    stock: 200,
    lowStockThreshold: 30,
    createdAt: '2024-01-25T08:00:00Z',
    updatedAt: '2024-02-03T16:00:00Z',
  },
  {
    id: '4',
    name: 'Toner Cân Bằng Da',
    slug: 'toner-can-bang-da',
    sku: 'TON-BAL-001',
    shortDesc: 'Toner giúp cân bằng độ pH, se khít lỗ chân lông',
    basePrice: 250000,
    comparePrice: 300000,
    isActive: true,
    isFeatured: true,
    brand: { id: '1', name: 'LingBeauty', slug: 'lingbeauty' },
    category: { id: '4', name: 'Toner', slug: 'toner', parentId: null, isActive: true, sortOrder: 4 },
    primaryImage: '/images/products/toner.jpg',
    stock: 12,
    lowStockThreshold: 20,
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-02-05T09:00:00Z',
  },
  {
    id: '5',
    name: 'Kem Dưỡng Ẩm Ban Đêm',
    slug: 'kem-duong-am-ban-dem',
    sku: 'CRM-NIT-001',
    shortDesc: 'Kem dưỡng ẩm chuyên sâu, phục hồi da qua đêm',
    basePrice: 520000,
    comparePrice: 620000,
    isActive: false,
    isFeatured: false,
    brand: { id: '3', name: 'GlowUp', slug: 'glowup' },
    category: { id: '5', name: 'Dưỡng ẩm', slug: 'duong-am', parentId: null, isActive: true, sortOrder: 5 },
    primaryImage: '/images/products/night-cream.jpg',
    stock: 0,
    lowStockThreshold: 10,
    createdAt: '2024-01-10T14:00:00Z',
    updatedAt: '2024-02-04T17:00:00Z',
  },
  {
    id: '6',
    name: 'Mặt Nạ Đất Sét',
    slug: 'mat-na-dat-set',
    sku: 'MSK-CLY-001',
    shortDesc: 'Mặt nạ đất sét giúp làm sạch sâu, kiểm soát dầu',
    basePrice: 150000,
    comparePrice: 180000,
    isActive: true,
    isFeatured: false,
    brand: { id: '2', name: 'PureSkin', slug: 'pureskin' },
    category: { id: '6', name: 'Mặt nạ', slug: 'mat-na', parentId: null, isActive: true, sortOrder: 6 },
    primaryImage: '/images/products/clay-mask.jpg',
    stock: 45,
    lowStockThreshold: 15,
    createdAt: '2024-01-28T11:00:00Z',
    updatedAt: '2024-02-05T10:00:00Z',
  },
];

/**
 * Mock categories data
 */
export const mockAdminCategories: IAdminCategoryDataType[] = [
  {
    id: '1',
    name: 'Chăm sóc da',
    slug: 'cham-soc-da',
    parentId: null,
    isActive: true,
    sortOrder: 1,
    children: [
      { id: '1-1', name: 'Serum', slug: 'serum', parentId: '1', isActive: true, sortOrder: 1 },
      { id: '1-2', name: 'Toner', slug: 'toner', parentId: '1', isActive: true, sortOrder: 2 },
      { id: '1-3', name: 'Dưỡng ẩm', slug: 'duong-am', parentId: '1', isActive: true, sortOrder: 3 },
      { id: '1-4', name: 'Làm sạch', slug: 'lam-sach', parentId: '1', isActive: true, sortOrder: 4 },
    ],
  },
  {
    id: '2',
    name: 'Chống nắng',
    slug: 'chong-nang',
    parentId: null,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: '3',
    name: 'Mặt nạ',
    slug: 'mat-na',
    parentId: null,
    isActive: true,
    sortOrder: 3,
  },
  {
    id: '4',
    name: 'Trang điểm',
    slug: 'trang-diem',
    parentId: null,
    isActive: true,
    sortOrder: 4,
    children: [
      { id: '4-1', name: 'Son môi', slug: 'son-moi', parentId: '4', isActive: true, sortOrder: 1 },
      { id: '4-2', name: 'Phấn nền', slug: 'phan-nen', parentId: '4', isActive: true, sortOrder: 2 },
      { id: '4-3', name: 'Mascara', slug: 'mascara', parentId: '4', isActive: true, sortOrder: 3 },
    ],
  },
];

/**
 * Mock brands data
 */
export const mockAdminBrands: IAdminBrandDataType[] = [
  { id: '1', name: 'LingBeauty', slug: 'lingbeauty', logo: '/images/brands/lingbeauty.png' },
  { id: '2', name: 'PureSkin', slug: 'pureskin', logo: '/images/brands/pureskin.png' },
  { id: '3', name: 'GlowUp', slug: 'glowup', logo: '/images/brands/glowup.png' },
  { id: '4', name: 'NatureLux', slug: 'naturelux', logo: '/images/brands/naturelux.png' },
];
