import {
  IAdminUserDataType,
  IAdminRoleDataType,
  IAdminPermissionDataType,
} from '@/lib/types/interfaces/apis/admin-user.interfaces';

/**
 * Mock permissions data
 */
export const mockAdminPermissions: IAdminPermissionDataType[] = [
  // Products
  { id: 'p1', name: 'products.view', description: 'Xem sản phẩm', category: 'products' },
  { id: 'p2', name: 'products.create', description: 'Tạo sản phẩm', category: 'products' },
  { id: 'p3', name: 'products.edit', description: 'Sửa sản phẩm', category: 'products' },
  { id: 'p4', name: 'products.delete', description: 'Xóa sản phẩm', category: 'products' },
  // Categories
  { id: 'c1', name: 'categories.view', description: 'Xem danh mục', category: 'categories' },
  { id: 'c2', name: 'categories.create', description: 'Tạo danh mục', category: 'categories' },
  { id: 'c3', name: 'categories.edit', description: 'Sửa danh mục', category: 'categories' },
  { id: 'c4', name: 'categories.delete', description: 'Xóa danh mục', category: 'categories' },
  // Inventory
  { id: 'i1', name: 'inventory.view', description: 'Xem kho hàng', category: 'inventory' },
  { id: 'i2', name: 'inventory.adjust', description: 'Điều chỉnh tồn kho', category: 'inventory' },
  // Users
  { id: 'u1', name: 'users.view', description: 'Xem người dùng', category: 'users' },
  { id: 'u2', name: 'users.create', description: 'Tạo người dùng', category: 'users' },
  { id: 'u3', name: 'users.edit', description: 'Sửa người dùng', category: 'users' },
  { id: 'u4', name: 'users.ban', description: 'Cấm người dùng', category: 'users' },
  { id: 'u5', name: 'users.delete', description: 'Xóa người dùng', category: 'users' },
  // Roles
  { id: 'r1', name: 'roles.view', description: 'Xem vai trò', category: 'roles' },
  { id: 'r2', name: 'roles.manage', description: 'Quản lý vai trò', category: 'roles' },
];

/**
 * Mock roles data
 */
export const mockAdminRoles: IAdminRoleDataType[] = [
  {
    id: '1',
    name: 'Super Admin',
    description: 'Quyền truy cập đầy đủ vào hệ thống',
    permissions: mockAdminPermissions,
    isSystem: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Product Manager',
    description: 'Quản lý sản phẩm, danh mục và kho hàng',
    permissions: mockAdminPermissions.filter((p) =>
      ['products', 'categories', 'inventory'].includes(p.category),
    ),
    isSystem: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'User Manager',
    description: 'Quản lý người dùng và quyền truy cập',
    permissions: mockAdminPermissions.filter((p) =>
      ['users', 'roles'].includes(p.category),
    ),
    isSystem: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'Viewer',
    description: 'Chỉ xem, không có quyền chỉnh sửa',
    permissions: mockAdminPermissions.filter((p) => p.name.endsWith('.view')),
    isSystem: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

/**
 * Mock users data for admin dashboard
 */
export const mockAdminUsers: IAdminUserDataType[] = [
  {
    id: '1',
    email: 'admin@lingbeauty.com',
    firstName: 'Admin',
    lastName: 'LingBeauty',
    phone: '0901234567',
    username: 'admin',
    avatar: null,
    isActive: true,
    isVerified: true,
    isBanned: false,
    isEmailVerified: true,
    isPhoneVerified: true,
    emailVerifiedAt: '2024-01-01T00:00:00Z',
    phoneVerifiedAt: '2024-01-01T00:00:00Z',
    roles: [mockAdminRoles[0]],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-02-01T00:00:00Z',
  },
  {
    id: '2',
    email: 'nguyen.van.a@email.com',
    firstName: 'Văn A',
    lastName: 'Nguyễn',
    phone: '0912345678',
    username: 'nguyenvana',
    avatar: null,
    isActive: true,
    isVerified: true,
    isBanned: false,
    isEmailVerified: true,
    isPhoneVerified: false,
    emailVerifiedAt: '2024-01-15T10:00:00Z',
    phoneVerifiedAt: null,
    roles: [mockAdminRoles[3]],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-02-02T14:00:00Z',
  },
  {
    id: '3',
    email: 'tran.thi.b@email.com',
    firstName: 'Thị B',
    lastName: 'Trần',
    phone: '0923456789',
    username: 'tranthib',
    avatar: null,
    isActive: true,
    isVerified: true,
    isBanned: false,
    isEmailVerified: true,
    isPhoneVerified: true,
    emailVerifiedAt: '2024-01-20T09:00:00Z',
    phoneVerifiedAt: '2024-01-21T11:00:00Z',
    roles: [mockAdminRoles[1]],
    createdAt: '2024-01-20T09:00:00Z',
    updatedAt: '2024-02-03T16:00:00Z',
  },
  {
    id: '4',
    email: 'le.van.c@email.com',
    firstName: 'Văn C',
    lastName: 'Lê',
    phone: '0934567890',
    username: 'levanc',
    avatar: null,
    isActive: false,
    isVerified: false,
    isBanned: true,
    isEmailVerified: true,
    isPhoneVerified: false,
    emailVerifiedAt: '2024-01-25T08:00:00Z',
    phoneVerifiedAt: null,
    roles: [],
    createdAt: '2024-01-25T08:00:00Z',
    updatedAt: '2024-02-04T17:00:00Z',
  },
  {
    id: '5',
    email: 'pham.thi.d@email.com',
    firstName: 'Thị D',
    lastName: 'Phạm',
    phone: '0945678901',
    username: 'phamthid',
    avatar: null,
    isActive: true,
    isVerified: true,
    isBanned: false,
    isEmailVerified: true,
    isPhoneVerified: true,
    emailVerifiedAt: '2024-02-01T10:00:00Z',
    phoneVerifiedAt: '2024-02-01T12:00:00Z',
    roles: [mockAdminRoles[2]],
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-02-05T09:00:00Z',
  },
  {
    id: '6',
    email: 'hoang.van.e@email.com',
    firstName: 'Văn E',
    lastName: 'Hoàng',
    phone: '0956789012',
    username: 'hoangvane',
    avatar: null,
    isActive: true,
    isVerified: false,
    isBanned: false,
    isEmailVerified: false,
    isPhoneVerified: false,
    emailVerifiedAt: null,
    phoneVerifiedAt: null,
    roles: [],
    createdAt: '2024-02-05T14:00:00Z',
    updatedAt: '2024-02-05T14:00:00Z',
  },
];
